{
    'name':'Educational ERP',
    'version': '13.0.1.1.2',
    'summary': 'Core module of Educational ERP.',
    'description':'Core module of Educational ERP.',
    'category': 'Educational',
    'author': 'Rakib Hasan',
    'depends':[],
    'data':[],
    'demo':[],
    'images':[],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
}